@EventManagment.Api_HostAddress = http://localhost:5160

GET {{EventManagment.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{EventManagment.Api_HostAddress}}/api/event
Content-Type: application/json

{
  "eventName": "Test Event",
  "eventDescription": "A test event for demonstration purposes",
  "eventStartDate": "2023-10-01T00:00:00",
  "eventEndDate": "2023-10-01T23:59:59"
}
